version: '3.8'
networks:
  my-bridge-network:
    driver: bridge
services:
  tomcat:
    platform: linux/amd64
    image: tomcat:8.5.46-jdk8-openjdk
    scale: 2
    volumes:
     - ../sample:/usr/local/tomcat/webapps/

  nginx:
    platform: linux/amd64
    image: nginx:1.18.0
    container_name: nginx
    restart: always
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - '10001:80'

