version: '3.8'
networks:
  my-bridge-network:
    driver: bridge
services:
  tomcat1:
    image: tomcat:8.5.46-jdk8-openjdk
    container_name: tomcat1
    ports:
      - "10002:8080"
    volumes:
     - ../sample:/usr/local/tomcat/webapps/

  tomcat2:
    image: tomcat:8.5.46-jdk8-openjdk
    container_name: tomcat2
    ports:
      - "10003:8080"
    volumes:
     - ../sample/:/usr/local/tomcat/webapps/

  nginx:
    image: nginx:1.18.0
    container_name: nginx
    restart: always
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - '10001:80'

